### ISSUE TITLE
Feature request: Implement COBS/R

### ISSUE THREAD

**Issue by cmcqueen** [awelkie/cobs.rs#13]
Please consider implementing [COBS/R](https://pythonhosted.org/cobs/cobsr-intro.html) which is a small variant of COBS that can often eliminate the +1-byte encoding overhead of COBS. I have implemented it in [C](/cmcqueen/cobs-c) and in [Python](/cmcqueen/cobs-python).

**Comment by jamesmunns** [comment]
Hi @cmcqueen, I'm not too familiar with COBS/R, and haven't needed it in my applications, however if you are interested in implementing it and submitting it as a PR, I'd be happy to review it.

Feel free to let me know if you run into any challenges with it.
