### ISSUE TITLE
Transferring ownership

### ISSUE THREAD

**Issue by jamesmunns** [awelkie/cobs.rs#14]
Hey @awelkie, I own the `postcard-cobs` crate, which is a fork of this one, and I am looking at implementing a couple different variations of cobs. Would you be interested in adding me as a crate or repo owner, so I can help with maintenance?

Thanks!

**Comment by jamesmunns** [comment]
As a note (I'll keep this open for now), @awelkie has transferred ownership of this crate to me. I'll plan on getting a new release out in the near future.

**Comment by cmcqueen** [comment]
Hello @jamesmunns, what variations do you have in mind? I submitted a feature request for COBS/R in issue #13. Is that a variation you could do?

**Comment by cmcqueen** [comment]
Hello @jamesmunns how is this transfer of ownership going? I don't see any new release in crates.io yet.

Could you clarify which git repository new development will occur in? Do you have permissions to https://github.com/awelkie/cobs.rs, or will you move development to your own https://github.com/jamesmunns/cobs.rs or other?

**Comment by cmcqueen** [comment]
@jamesmunns please do maintain this repo and the Rust cobs crate, since you have taken ownership of it.

**Comment by jamesmunns** [comment]
Hi @cmcqueen, answering some of your questions:

> what variations do you have in mind? I submitted a feature request for COBS/R in issue https://github.com/awelkie/cobs.rs/issues/13. Is that a variation you could do?

I had been considering moving `rlercobs` from [this repo](https://github.com/jamesmunns/kolben) into the cobs rs repo, as well as potentially re-exporting dirbaio's [rcobs](https://github.com/Dirbaio/rcobs) and [rzcobs](https://github.com/Dirbaio/rzcobs) crates, if they could be reasonably consistent with eachother.

WRT: `COBS/R`, I mentioned my response in #13, but I am unlikely to implement this algorithm unless I need it for something I am doing. If you would like to PR it, I would happily review it.

> how is this transfer of ownership going? ... Could you clarify which git repository new development will occur in?

I plan to archive my old repo, and move this repo into my space. There has not been a release yet, as I have had an unexpectedly busy year. I hope to schedule some work on postcard, and re-aligning it with a re-merged cobs later this spring or so.

> please do maintain this repo and the Rust cobs crate, since you have taken ownership of it.

I'm not sure what you are requesting here. You haven't opened a bug report, only a feature request. I'm happy to maintain this repository as it relates to my use of it (primarily for postcard, which I use heavily), and am happy to review any feature additions and merge any bug fixes. If implementation of a new algorithm is something you need assistance with, I'd be happy to chat about setting up an estimate/statement of work for that.

**Comment by jamesmunns** [comment]
I've picked up development in https://github.com/jamesmunns/cobs.rs. I'm going to go ahead and close this issue.

**Comment by cmcqueen** [comment]
I would like to report an issue in https://github.com/jamesmunns/cobs.rs but the "Issues" tab isn't enabled.
