### ISSUE TITLE
feature request: asynchronous API for decoding

### ISSUE THREAD

**Issue by astraw** [awelkie/cobs.rs#5]
Hi, I'd like to use COBS in the [framed-serial](https://github.com/astraw/framed-serial) crate, but to do so, I need asynchronous decoding. Specifically, I want to pass in each incoming byte as it arrives to check for the completion of a valid frame.

**Comment by awelkie** [comment]
Yeah, I agree that would be a nice addition. I accept PRs, or I might get to this in the upcoming weeks.

**Comment by awelkie** [comment]
So there are two APIs that I can think of to implement this.

Option 1 is where the user is responsible for handing the `Decoder` only non-sentinel bytes. For every non-sentinel byte added, the decoder will return an `Option<u8>`. The `Decoder` could also have a method to determine whether a frame end would be acceptable or not. Something like this:

```rust
// Option 1
pub struct Decoder;

impl Decoder {
    pub fn new() -> Self;

    pub fn add_byte(&mut self, byte: u8) -> Option<u8> {
        assert_ne!(byte, 0);
        ...
    }

    pub fn is_complete(&self) -> bool;
}
```

Option 2 is where the user passes every byte - including sentinel bytes - to the `Decoder`. The `Decoder` will then determine frame boundaries and whether or not the frames decoded without errors. Something like this:

```rust
// Option 2
enum DecodeResult {
    None,
    Byte(u8),
    FrameEnd,
    FrameError,
}

impl Decoder {
    pub fn new() -> Self;

    pub fn add_byte(&mut self, byte: u8) -> DecodeResult;
}
```

I'm torn between the two at the moment. The fundamental question is whether this library should be responsible for actually doing the framing (i.e. monitoring for sentinel bytes) or just doing the decoding of the frames. I'm leaning towards Option 1, but do you have any thoughts?

**Comment by astraw** [comment]
I agree that the question boils down to whether this lib should be responsible for the framing. I actually lean towards Option 2, because a) why would you use an online COBS algo if not also for framing? And b) what is gained by not having one blessed way to do framing? In other words, could you imagine two callers so divergent that they would need to implement framing differently and in a way that this library couldn't easily accommodate?

**Comment by awelkie** [comment]
That's a good point. I can't actually think of a scenario where someone would need to implement framing in a different way than this library would in Option 2.

Also, either option can be emulated by using the other. For example, you can get the same behavior of Option 1 using a little logic on top of Option 2, and vice versa. Given that neither option is more powerful than the other, the decision really comes down to which one gives a nicer interface for more use-cases, and I think Option 2 wins there.

I'll go ahead and implement Option 2, then. Thanks for the feedback!

**Comment by Meyermagic** [comment]
I'm using cobs.rs for serial framing in my own project, and wrote up a Tokio Codec implementation using cobs.rs while refactoring today. It's not tested yet, doesn't have error handling, etc, and I'm working on it out-of-tree for now, but I'd be happy to contribute it back, perhaps behind a cargo feature.

If you're interested, let me know any testing / api / code requirements / suggestions you have and I'll send you a pull request: https://gist.github.com/Meyermagic/c04d2e8095f45bd6631a167b4bd889c4

**Comment by fluffysquirrels** [comment]
@Meyermagic Your gist looks like great progress on this. I'd love to see it integrated behind a feature flag (to enable embedded use).

I think returning Vec<u8> from the Decoder is fine; consumers have plenty of options to use it from there. I agree the Encoder item type should be a slice.

**Comment by jamesmunns** [comment]
I'm currently working on having a no_std friendly encoder/decoder here: https://github.com/ferrous-systems/cobs.rs/pull/1/files - I plan submit this as a PR upstream if there is interest :)

**Comment by awelkie** [comment]
Yeah, that would be great!
